In [1]:
import pandas as pd

df = pd.read_parquet("/Users/yogamtchokni/Library/CloudStorage/OneDrive-DIWBerlin/Projekte/pyautocausal/pyautocausal/examples/data/criteo_sample.parquet")

In [2]:
df['id'] = df.index

In [4]:
df

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,treatment,conversion,visit,exposure,id
309434,25.936762,10.059654,9.006136,4.679882,10.280525,4.115453,-7.822229,4.833815,3.860579,13.190056,5.300375,-0.168679,1,0,0,0,309434
1399122,26.158155,10.059654,8.214383,4.679882,10.280525,4.115453,-1.288207,4.833815,3.971858,13.190056,5.300375,-0.168679,1,0,0,0,1399122
7222090,12.616365,10.059654,8.597161,4.679882,10.280525,4.115453,0.294443,4.833815,3.927254,21.416100,5.300375,-0.168679,1,0,0,0,7222090
9831069,25.563096,10.059654,8.214383,4.679882,10.280525,4.115453,-1.288207,4.833815,3.971858,13.190056,5.300375,-0.168679,1,0,0,0,9831069
7729579,25.358956,10.059654,8.214383,4.679882,10.280525,4.115453,-3.993764,4.833815,3.971858,13.190056,5.300375,-0.168679,1,0,0,0,7729579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10427146,26.540569,10.059654,8.214383,4.679882,10.280525,4.115453,-1.288207,4.833815,3.971858,13.190056,5.300375,-0.168679,0,0,0,0,10427146
11987536,25.824977,10.059654,8.214383,4.679882,10.280525,4.115453,-1.288207,4.833815,3.971858,13.190056,5.300375,-0.168679,1,0,0,0,11987536
5046205,12.616365,10.059654,8.968967,4.679882,11.561050,4.115453,0.294443,4.833815,3.843683,13.190056,6.357755,-0.168679,1,0,0,0,5046205
13771927,12.616365,10.059654,8.345486,4.679882,11.973287,4.115453,0.294443,4.833815,3.717101,50.905085,5.596672,-0.337358,1,0,1,0,13771927
10311065,20.604680,10.059654,8.488839,4.679882,10.280525,4.115453,-8.058865,4.833815,3.809159,29.214161,5.300375,-0.168679,0,0,1,0,10311065

In [15]:
df

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,treatment,conversion,visit,exposure,id
0,12.616365,10.059654,8.976429,4.679882,10.280525,4.115453,0.294443,4.833815,3.955396,13.190056,5.300375,-0.168679,1,0,0,0,0
1,12.616365,10.059654,9.002689,4.679882,10.280525,4.115453,0.294443,4.833815,3.955396,13.190056,5.300375,-0.168679,1,0,0,0,1
2,12.616365,10.059654,8.964775,4.679882,10.280525,4.115453,0.294443,4.833815,3.955396,13.190056,5.300375,-0.168679,1,0,0,0,2
3,12.616365,10.059654,9.002801,4.679882,10.280525,4.115453,0.294443,4.833815,3.955396,13.190056,5.300375,-0.168679,1,0,0,0,3
4,12.616365,10.059654,9.037999,4.679882,10.280525,4.115453,0.294443,4.833815,3.955396,13.190056,5.300375,-0.168679,1,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13979587,26.297764,10.059654,9.006250,4.679882,10.280525,4.115453,-3.282109,4.833815,3.839578,13.190056,5.300375,-0.168679,1,0,0,0,13979587
13979588,12.642207,10.679513,8.214383,-1.700105,10.280525,3.013064,-13.955150,6.269026,3.971858,13.190056,5.300375,-0.168679,1,0,0,1,13979588
13979589,12.976557,10.059654,8.381868,0.842442,11.029584,4.115453,-8.281971,4.833815,3.779212,23.570168,6.169187,-0.168679,1,0,1,0,13979589
13979590,24.805064,10.059654,8.214383,4.679882,10.280525,4.115453,-1.288207,4.833815,3.971858,13.190056,5.300375,-0.168679,1,0,0,0,13979590
13979591,12.616365,10.059654,8.214383,4.679882,10.280525,3.013064,0.294443,9.332563,3.971858,13.190056,5.300375,-0.168679,1,0,0,0,13979591